# Lab 5
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/maxmarumbwa/geog-510-exercises/blob/lab_5/book/labs/lab_05.ipynb)

## Exercise 1: Calculating Distances with Functions

- Define a function `calculate_distance` that takes two geographic coordinates (latitude and longitude) and returns the distance between them using the Haversine formula.
- Use this function to calculate the distance between multiple pairs of coordinates.

In [ ]:
import math
def calculate_distance(coord1, coord2):
    R = 6371.0  # Radius of the Earth in kilometers
    lat1, lon1 = coord1
    lat2, lon2 = coord2
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    # Calculate the differences
    dlat = lat2 - lat1
    dlon = lon2 - lon1
        # Haversine formula
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
      # Distance in kilometers
    distance = R * c
    return distance
#calculate_distance((48.8567, 2.3508), (51.5072, -0.1275)) 


#### calculate the distance between multiple pairs of coordinates. 
def calculate_multiple_distances(coords):
    results = []
    for coord1, coord2 in coords:
        distance = calculate_distance(coord1, coord2)
        results.append((coord1, coord2, distance))
    return results

# Example usage:
coordinates = [
    ((22.6756, 32.2334), (49.3300, 51.1343)),
    ((56.2343, 23.4564), (34.0132, 12.5113300)), 
    ((34.3235, -18.2311), (71.2776, -74.005974)),   
]

# Calculate and print the distances
distances = calculate_multiple_distances(coordinates)
for start, end, distance in distances:
    print(f"Distance between {start} and {end}: {distance:.2f} km")

## Exercise 2: Batch Distance Calculation

- Create a function `batch_distance_calculation` that accepts a list of coordinate pairs and returns a list of distances between consecutive pairs.
- Test the function with a list of coordinates representing several cities.

In [ ]:
# Calculate the distance between multiple pairs of coordinates using a different approach.
def batch_distance_calculation(coordinates):
    distances = []
    for i in range(len(coordinates) - 1):
        distance = calculate_distance(coordinates[i], coordinates[i + 1])
        distances.append(distance)
    return distances

# Example usage:
coordinates = [
    (52.2296756, 21.0122287),  # Warsaw
    (41.8919300, 12.5113300),  # Rome
    (48.856613, 2.352222),     # Paris
    (40.712776, -74.005974),   # NYC
]

# Calculate and return the distances
distances = batch_distance_calculation(coordinates)
print(distances)


## Exercise 3: Creating and Using a Point Class

- Define a `Point` class to represent a geographic point with attributes `latitude`, `longitude`, and `name`.
- Add a method `distance_to` that calculates the distance from one point to another.
- Instantiate several `Point` objects and calculate the distance between them.

In [ ]:
import math

class Point:
    def __init__(self, latitude, longitude, name=""):
        self.latitude = latitude
        self.longitude = longitude
        self.name = name

    def distance_to(self, other):
        """Calculates the great-circle distance between two points using the Haversine formula."""
        R = 6371  # Radius of Earth in kilometers
        lat1, lon1 = math.radians(self.latitude), math.radians(self.longitude)
        lat2, lon2 = math.radians(other.latitude), math.radians(other.longitude)
        
        dlat = lat2 - lat1
        dlon = lon2 - lon1
        
        a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        
        return R * c  # Distance in kilometers

# Example usage
point1 = Point(-17.8292, 31.0522, "Harare")
point2 = Point(-19.0154, 29.1549, "Bulawayo")

print(f"Distance from {point1.name} to {point2.name}: {point1.distance_to(point2):.2f} km")


## Exercise 4: Reading and Writing Files

- Write a function `read_coordinates` that reads a file containing a list of coordinates (latitude, longitude) and returns them as a list of tuples.
- Write another function `write_coordinates` that takes a list of coordinates and writes them to a new file.
- Ensure that both functions handle exceptions, such as missing files or improperly formatted data.

In [67]:
# Create a sample coordinates.txt file
sample_data = """35.6895,139.6917
34.0522,-118.2437
51.5074,-0.1278
-33.8688,151.2093
48.8566,2.3522"""

output_file = "coordinates.txt"

try:
    with open(output_file, "w") as file:
        file.write(sample_data)
    print(f"Sample file '{output_file}' has been created successfully.")
except Exception as e:
    print(f"An error occurred while creating the file: {e}")

Sample file 'coordinates.txt' has been created successfully.


In [68]:
import csv
import os

def read_coordinates(file_path):
    """Reads a CSV file containing latitude and longitude and returns a list of tuples."""
    coordinates = []
    
    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found.")
        return coordinates  # Return empty list if file is missing

    try:
        with open(file_path, newline='', encoding='utf-8') as csvfile:
            reader = csv.reader(csvfile)
            header = next(reader, None)  # Read header (if present)
            
            for row in reader:
                if len(row) != 2:
                    print(f"Skipping invalid row (wrong number of columns): {row}")
                    continue
                try:
                    lat, lon = float(row[0]), float(row[1])
                    coordinates.append((lat, lon))
                except ValueError:
                    print(f"Skipping invalid row (non-numeric values): {row}")
    except Exception as e:
        print(f"Error reading file: {e}")

    return coordinates


def write_coordinates(file_path, coordinates):
    """Writes a list of (latitude, longitude) tuples to a CSV file."""
    try:
        with open(file_path, mode='w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["latitude", "longitude"])  # Write header
            
            for lat, lon in coordinates:
                writer.writerow([lat, lon])
                
        print(f"Coordinates successfully written to '{file_path}'")
    except Exception as e:
        print(f"Error writing file: {e}")



# Read from file
read_coords = read_coordinates("coordinates.txt")
print(read_coords)

# Example coordinate list
coords = [(-17.8292, 31.0522), (-18.1234, 30.9876), (-19.5678, 32.1234), (-20.3456, 29.8765)]
# Write to file
write_coordinates("new_coordinates.csv", coords)

[(34.0522, -118.2437), (51.5074, -0.1278), (-33.8688, 151.2093), (48.8566, 2.3522)]
Coordinates successfully written to 'new_coordinates.csv'


## Exercise 5: Processing Coordinates from a File

- Create a function that reads coordinates from a file and uses the `Point` class to create `Point` objects.
- Calculate the distance between each consecutive pair of points and write the results to a new file.
- Ensure the function handles file-related exceptions and gracefully handles improperly formatted lines.

In [ ]:
# Create a sample coordinates.txt file
sample_data = """35.6895,139.6917
34.0522,-118.2437
51.5074,-0.1278
-33.8688,151.2093
48.8566,2.3522"""

output_file = "coordinates.txt"

try:
    with open(output_file, "w") as file:
        file.write(sample_data)
    print(f"Sample file '{output_file}' has been created successfully.")
except Exception as e:
    print(f"An error occurred while creating the file: {e}")

In [ ]:
import math

def haversine(lat1, lon1, lat2, lon2):
    """Calculate the great-circle distance between two points on the Earth."""
    R = 6371  # Radius of the Earth in km
    
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    return R * c

def process_coordinates(input_file, output_file):
    try:
        with open(input_file, "r") as file:
            lines = file.readlines()
        
        points = []
        for line in lines:
            try:
                lat, lon = map(float, line.strip().split(","))
                points.append((lat, lon))
            except ValueError:
                print(f"Skipping invalid line: {line.strip()}")
        
        distances = []
        for i in range(len(points) - 1):
            lat1, lon1 = points[i]
            lat2, lon2 = points[i + 1]
            distance = haversine(lat1, lon1, lat2, lon2)
            distances.append(f"Distance between {points[i]} and {points[i+1]}: {distance:.2f} km")
        
        with open(output_file, "w") as file:
            file.write("\n".join(distances))
        
        print(f"Distances written to '{output_file}' successfully.")
    except FileNotFoundError:
        print(f"Error: The file '{input_file}' was not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Run the function
process_coordinates("coordinates.txt", "distances.txt")

## Exercise 6: Exception Handling in Data Processing

- Modify the `batch_distance_calculation` function to handle exceptions that might occur during the calculation, such as invalid coordinates.
- Ensure the function skips invalid data and continues processing the remaining data.

In [ ]:
import math

def calculate_distance(coord1, coord2):
    R = 6371.0  # Radius of the Earth in kilometers
    lat1, lon1 = coord1
    lat2, lon2 = coord2
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    # Calculate the differences
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    # Haversine formula
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    # Distance in kilometers
    distance = R * c
    return distance

def batch_distance_calculation(coordinates):
    distances = []
    for i in range(len(coordinates) - 1):
        try:
            # Ensure valid coordinates (latitude: -90 to 90, longitude: -180 to 180)
            if not (-90 <= coordinates[i][0] <= 90 and -180 <= coordinates[i][1] <= 180):
                print(f"Invalid coordinates: {coordinates[i]}, skipping.")
                continue
            if not (-90 <= coordinates[i + 1][0] <= 90 and -180 <= coordinates[i + 1][1] <= 180):
                print(f"Invalid coordinates: {coordinates[i + 1]}, skipping.")
                continue

            # Calculate the distance between the current and next pair of coordinates
            distance = calculate_distance(coordinates[i], coordinates[i + 1])
            distances.append(distance)

        except Exception as e:
            print(f"Error processing coordinates {coordinates[i]} and {coordinates[i + 1]}: {e}")
            continue  # Skip to the next pair in case of error
    
    return distances

# Example usage:
coordinates = [
    (52.2296756, 21.0122287),  # Warsaw
    (41.8919300, 12.5113300),  # Rome
    (48.856613, 2.352222),     # Paris
    (40.712776, -74.005974),   # NYC
    (1000, 2000),              # Invalid coordinates
]

# Calculate and return the distances
distances = batch_distance_calculation(coordinates)
print(distances)


## Exercise 7: NumPy Array Operations and Geospatial Coordinates

In this exercise, you will work with NumPy arrays representing geospatial coordinates (latitude and longitude) and perform basic array operations.

1. Create a 2D NumPy array containing the latitude and longitude of the following cities: Tokyo (35.6895, 139.6917), New York (40.7128, -74.0060), London (51.5074, -0.1278), and Paris (48.8566, 2.3522).
2. Convert the latitude and longitude values from degrees to radians using np.radians().
3. Calculate the element-wise difference between Tokyo and the other cities' latitude and longitude in radians.

In [ ]:
import numpy as np

# Step 1: Create the 2D NumPy array with the cities' coordinates
cities = np.array([
    [35.6895, 139.6917],   # Tokyo
    [40.7128, -74.0060],   # New York
    [51.5074, -0.1278],    # London
    [48.8566, 2.3522]      # Paris
])

# Step 2: Convert the latitude and longitude values from degrees to radians
radians_cities = np.radians(cities)

# Step 3: Calculate the element-wise difference between Tokyo and the other cities
tokyo_radians = radians_cities[0]
other_cities_radians = radians_cities[1:]
differences = other_cities_radians - tokyo_radians

print("Differences in radians (Tokyo vs others):")
print(differences)

## Exercise 8: Pandas DataFrame Operations with Geospatial Data

In this exercise, you'll use Pandas to load and manipulate a dataset containing city population data, and then calculate and visualize statistics.

1. Load the world cities dataset from this URL using Pandas: https://github.com/opengeos/datasets/releases/download/world/world_cities.csv
2. Display the first 5 rows and check for missing values.
3. Filter the dataset to only include cities with a population greater than 1 million.
4. Group the cities by their country and calculate the total population for each country.
5. Sort the cities by population in descending order and display the top 10 cities.

In [ ]:
import pandas as pd

# 1. Load the dataset
url = "https://github.com/opengeos/datasets/releases/download/world/world_cities.csv"
df = pd.read_csv(url)

# 2. Display first 5 rows and check for missing values
print("First 5 rows:")
print(df.head())
print("\nMissing values per column:")
print(df.isnull().sum())

# 3. Filter cities with population > 1 million
large_cities = df[df['population'] > 1_000_000]



In [ ]:
# 4. Group by country and calculate total population
country_population = large_cities.groupby('country')['population'].sum().reset_index()
country_population.columns = ['Country', 'Total Population']
print("\nTotal population by country:")
print(country_population)

# 5. Sort cities by population and display top 10
top_cities = large_cities.sort_values('population', ascending=False).head(10)
print("\n Top ten populated cities")
print(top_cities)

## Exercise 9: Creating and Manipulating GeoDataFrames with GeoPandas

This exercise focuses on creating and manipulating GeoDataFrames, performing spatial operations, and visualizing the data.

1. Load the New York City building dataset from the GeoJSON file using GeoPandas: https://github.com/opengeos/datasets/releases/download/places/nyc_buildings.geojson
2. Create a plot of the building footprints and color them based on the building height (use the `height_MS` column).
3. Create an interactive map of the building footprints and color them based on the building height (use the `height_MS` column).
4. Calculate the average building height (use the `height_MS` column).
5. Select buildings with a height greater than the average height.
6. Save the GeoDataFrame to a new GeoJSON file.

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
import pandas as pd

# Load the dataset
url = "https://github.com/opengeos/datasets/releases/download/places/nyc_buildings.geojson"
gdf = gpd.read_file(url)

# Ensure 'height_MS' column is numeric
gdf['height_MS'] = pd.to_numeric(gdf['height_MS'], errors='coerce')

# Plot the building footprints colored by height
fig, ax = plt.subplots(figsize=(10, 10))
gdf.plot(column='height_MS', cmap='viridis', legend=True, ax=ax)
plt.title("New York City Building Heights")
plt.show()

# Create an interactive map
m = folium.Map(location=[40.7128, -74.0060], zoom_start=12)

# Add buildings to the map with colors based on height
folium.Choropleth(
    geo_data=gdf,
    name="Buildings",
    data=gdf,
    columns=[gdf.index, 'height_MS'],
    key_on="feature.id",
    fill_color="YlGnBu",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Building Height (meters)"
).add_to(m)

# Save the map
m.save("nyc_buildings_map.html")

# Calculate the average building height
avg_height = gdf['height_MS'].mean()
print(f"Average Building Height: {avg_height:.2f} meters")

# Select buildings taller than the average height
tall_buildings = gdf[gdf['height_MS'] > avg_height]

# Save the new dataset
tall_buildings.to_file("nyc_tall_buildings.geojson", driver="GeoJSON")


## Exercise 10: Combining NumPy, Pandas, and GeoPandas

This exercise requires you to combine the power of NumPy, Pandas, and GeoPandas to analyze and visualize spatial data.

1. Use Pandas to load the world cities dataset from this URL: https://github.com/opengeos/datasets/releases/download/world/world_cities.csv
2. Filter the dataset to include only cities with latitude values between -40 and 60 (i.e., cities located in the Northern Hemisphere or near the equator).
3. Create a GeoDataFrame from the filtered dataset by converting the latitude and longitude into geometries.
4. Reproject the GeoDataFrame to the Mercator projection (EPSG:3857).
5. Calculate the distance (in meters) between each city and the city of Paris.
6. Plot the cities on a world map, coloring the points by their distance from Paris.

In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt

# Load the dataset
url = "https://github.com/opengeos/datasets/releases/download/world/world_cities.csv"
df = pd.read_csv(url)

# Filter dataset for latitude values between -40 and 60
df_filtered = df[(df['latitude'] >= -40) & (df['latitude'] <= 60)]

# Create a GeoDataFrame
gdf = gpd.GeoDataFrame(
    df_filtered, geometry=gpd.points_from_xy(df_filtered.longitude, df_filtered.latitude), crs="EPSG:4326"
)

# Reproject to Mercator projection (EPSG:3857)
gdf_mercator = gdf.to_crs(epsg=3857)

# Define Paris coordinates and create a GeoDataFrame for Paris
paris_coords = (2.3522, 48.8566)  # Longitude, Latitude
paris_point = gpd.GeoDataFrame(
    {'city': ['Paris'], 'geometry': [Point(paris_coords)]}, crs="EPSG:4326"
).to_crs(epsg=3857)

# Calculate distances (in meters) between each city and Paris
gdf_mercator['distance_to_paris'] = gdf_mercator.geometry.distance(paris_point.geometry.iloc[0])

# Plot the cities, coloring them by distance from Paris
fig, ax = plt.subplots(figsize=(12, 8))
gdf_mercator.plot(column='distance_to_paris', cmap='viridis', legend=True, ax=ax, markersize=5)
paris_point.plot(ax=ax, color='red', markersize=50, label='Paris')
ax.set_title("World Cities Colored by Distance from Paris (Meters)")
plt.legend()
plt.show()


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.